### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/lrasm#34]
Write test cases and code iteratively: Accuracy

Comments
Great job! Each test was importing functions incorrectly. As a results, I had to drag and drop the coded function into the same directory. After this, i imported the code and the tests worked fine. 

Write test cases and code iteratively: Code Quality

Comments
Great test coverage, All the functions and tests are documented (docstrings and/or comments are present)

Exception handling: Code Quality

Comments
The exception handling is included in the function’s body for all the functions

**Comment by gutermanyair** [comment]
Thank you for this feedback!
