### ISSUE TITLE
Milestone #3 Feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/lrasm#38]
GitHub actions workflow for continuous integration for the Python project: Mechanics

Comments
ci and cd are working but the readme bagde is missing 

GitHub actions workflow for continuous deployment for the Python project: Mechanics

Comments
ci and cd are working but the readme bagde is missing 

Python package documentation: Reasoning

Comments
Readthedocs.org documentation is not present or it is not possible to know so because the link it was not provided clearly in the readme or as a link 

Specific expectations for this milestone: Mechanics
Comments
Song Yang only created 1 commit in Python repo

**Comment by gutermanyair** [comment]
Thank you for this Feedback!
